import assert from "node:assert/strict";
import { existsSync } from "node:fs";
import { mkdtemp, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { test } from "node:test";
import {
  DocumentNormalizationError,
  discoverDocumentFiles,
  inspectDocumentFile,
  normalizeDocumentArtifact
} from "../apps/dbos-worker/src/document-normalization";

async function withTempWorkdir(run: (workdir: string) => Promise<void>) {
  const workdir = await mkdtemp(path.join(os.tmpdir(), "honeycomb-document-normalization-"));
  try {
    await run(workdir);
  } finally {
    await rm(workdir, { recursive: true, force: true });
  }
}

test("Markdown becomes validated TXT and DOCX while preserving the source", async () => {
  await withTempWorkdir(async (workdir) => {
    const sourcePath = path.join(workdir, "report.md");
    const source = [
      "# 茶道研究报告",
      "",
      "这是一份可以交付的中文报告。",
      "",
      "- 历史背景",
      "- 当代传播",
      ""
    ].join("\n");
    await writeFile(sourcePath, source, "utf8");

    const text = await normalizeDocumentArtifact({
      sourcePath,
      workdir,
      deliverableIndex: 0,
      requestedFormat: "txt",
      title: "茶道研究报告"
    });
    assert.equal(text.format, "txt");
    assert.equal(text.transformed, true);
    assert.match(await readFile(text.filePath, "utf8"), /茶道研究报告/);
    assert.equal((await inspectDocumentFile(text.filePath)).format, "txt");

    const docx = await normalizeDocumentArtifact({
      sourcePath,
      workdir,
      deliverableIndex: 1,
      requestedFormat: "docx",
      title: "茶道研究报告"
    });
    const docxInspection = await inspectDocumentFile(docx.filePath);
    assert.equal(docxInspection.format, "docx");
    assert.ok((docxInspection.entryCount ?? 0) > 5);
    assert.equal((await readFile(docx.filePath)).subarray(0, 2).toString("ascii"), "PK");
    assert.equal(await readFile(sourcePath, "utf8"), source);

    await writeFile(docx.filePath, "interrupted document output", "utf8");
    const recovered = await normalizeDocumentArtifact({
      sourcePath,
      workdir,
      deliverableIndex: 1,
      requestedFormat: "docx",
      title: "茶道研究报告"
    });
    assert.equal(recovered.filePath, docx.filePath);
    assert.equal(recovered.reused, false);
    assert.equal((await inspectDocumentFile(recovered.filePath)).format, "docx");

    const reused = await normalizeDocumentArtifact({
      sourcePath,
      workdir,
      deliverableIndex: 1,
      requestedFormat: "docx",
      title: "茶道研究报告"
    });
    assert.equal(reused.filePath, docx.filePath);
    assert.equal(reused.checksumSha256, recovered.checksumSha256);
    assert.equal(reused.reused, true);
  });
});

test("ASCII Markdown becomes a parseable multi-block PDF", async () => {
  await withTempWorkdir(async (workdir) => {
    const sourcePath = path.join(workdir, "report.md");
    await writeFile(sourcePath, [
      "# Tea Research",
      "",
      "A durable report generated by Honeycomb.",
      "",
      "1. History",
      "2. Modern practice",
      ""
    ].join("\n"), "utf8");
    const pdf = await normalizeDocumentArtifact({
      sourcePath,
      workdir,
      deliverableIndex: 0,
      requestedFormat: "pdf",
      title: "Tea Research"
    });
    const inspection = await inspectDocumentFile(pdf.filePath);
    assert.equal(inspection.format, "pdf");
    assert.equal(inspection.pageCount, 1);
    assert.equal((await readFile(pdf.filePath)).subarray(0, 5).toString("ascii"), "%PDF-");
  });
});

test("Chinese PDF validates TTC PostScript names and falls back safely", {
  skip: !existsSync("C:\\Windows\\Fonts\\msyh.ttc") ||
    !existsSync("C:\\Windows\\Fonts\\simhei.ttf")
}, async () => {
  const previousPath = process.env.HONEYCOMB_DOCUMENT_PDF_FONT_PATH;
  const previousFace = process.env.HONEYCOMB_DOCUMENT_PDF_FONT_FACE;
  process.env.HONEYCOMB_DOCUMENT_PDF_FONT_PATH = "C:\\Windows\\Fonts\\msyh.ttc";
  process.env.HONEYCOMB_DOCUMENT_PDF_FONT_FACE = "MicrosoftYaHei";
  try {
    await withTempWorkdir(async (workdir) => {
      const sourcePath = path.join(workdir, "chinese-report.md");
      await writeFile(sourcePath, "# 茶道研究报告\n\n这是一份中文 PDF 交付测试。\n", "utf8");
      const pdf = await normalizeDocumentArtifact({
        sourcePath,
        workdir,
        deliverableIndex: 0,
        requestedFormat: "pdf",
        title: "茶道研究报告"
      });
      const inspection = await inspectDocumentFile(pdf.filePath);
      assert.equal(inspection.format, "pdf");
      assert.equal(inspection.pageCount, 1);
      assert.ok(inspection.sizeBytes > 1_000);

      process.env.HONEYCOMB_DOCUMENT_PDF_FONT_FACE = "Microsoft YaHei";
      const fallbackPdf = await normalizeDocumentArtifact({
        sourcePath,
        workdir,
        deliverableIndex: 1,
        requestedFormat: "pdf",
        title: "中文字体安全回退测试"
      });
      assert.equal((await inspectDocumentFile(fallbackPdf.filePath)).format, "pdf");
    });
  } finally {
    if (previousPath === undefined) delete process.env.HONEYCOMB_DOCUMENT_PDF_FONT_PATH;
    else process.env.HONEYCOMB_DOCUMENT_PDF_FONT_PATH = previousPath;
    if (previousFace === undefined) delete process.env.HONEYCOMB_DOCUMENT_PDF_FONT_FACE;
    else process.env.HONEYCOMB_DOCUMENT_PDF_FONT_FACE = previousFace;
  }
});

test("JSON and CSV are emitted only when the child text parses as that structure", async () => {
  await withTempWorkdir(async (workdir) => {
    const jsonSource = path.join(workdir, "json-source.md");
    await writeFile(jsonSource, "{\"tea\":\"longjing\",\"year\":2026}\n", "utf8");
    const json = await normalizeDocumentArtifact({
      sourcePath: jsonSource,
      workdir,
      deliverableIndex: 0,
      requestedFormat: "json",
      title: "Tea data"
    });
    assert.equal((await inspectDocumentFile(json.filePath)).format, "json");
    assert.deepEqual(JSON.parse(await readFile(json.filePath, "utf8")), {
      tea: "longjing",
      year: 2026
    });

    const csvSource = path.join(workdir, "csv-source.md");
    await writeFile(csvSource, "tea,year\nlongjing,2026\n", "utf8");
    const csv = await normalizeDocumentArtifact({
      sourcePath: csvSource,
      workdir,
      deliverableIndex: 1,
      requestedFormat: "csv",
      title: "Tea table"
    });
    assert.equal((await inspectDocumentFile(csv.filePath)).format, "csv");

    const invalidSource = path.join(workdir, "invalid.md");
    await writeFile(invalidSource, "This is prose, not JSON.", "utf8");
    await assert.rejects(
      normalizeDocumentArtifact({
        sourcePath: invalidSource,
        workdir,
        deliverableIndex: 2,
        requestedFormat: "json",
        title: "Invalid"
      }),
      (error: unknown) => error instanceof DocumentNormalizationError &&
        error.code === "document_json_invalid"
    );
  });
});

test("fake PDF and DOCX extensions do not pass structural inspection", async () => {
  await withTempWorkdir(async (workdir) => {
    const fakePdf = path.join(workdir, "fake.pdf");
    const fakeDocx = path.join(workdir, "fake.docx");
    await writeFile(fakePdf, "%PDF-1.7\nnot a real document\n%%EOF\n", "utf8");
    await writeFile(fakeDocx, Buffer.from([0x50, 0x4b, 0x03, 0x04, 1, 2, 3, 4]));
    await assert.rejects(
      inspectDocumentFile(fakePdf),
      (error: unknown) => error instanceof DocumentNormalizationError &&
        error.code === "document_pdf_invalid"
    );
    await assert.rejects(
      inspectDocumentFile(fakeDocx),
      (error: unknown) => error instanceof DocumentNormalizationError &&
        error.code === "document_ooxml_invalid"
    );
  });
});

test("document discovery keeps valid files, reports invalid files, and stays in the job root", async () => {
  await withTempWorkdir(async (workdir) => {
    const stageDir = path.join(workdir, "stages", "001-writing");
    await mkdir(path.join(stageDir, "nested"), { recursive: true });
    await writeFile(path.join(stageDir, "report.md"), "# Valid report\n", "utf8");
    await writeFile(path.join(stageDir, "nested", "notes.txt"), "Valid notes\n", "utf8");
    await writeFile(path.join(stageDir, "broken.pdf"), "not a pdf", "utf8");
    const discovery = await discoverDocumentFiles({ directory: stageDir, workdir });
    assert.deepEqual(
      discovery.files.map((file) => file.inspection.format).sort(),
      ["md", "txt"]
    );
    assert.equal(discovery.rejected.length, 1);

    const outside = await mkdtemp(path.join(os.tmpdir(), "honeycomb-document-outside-"));
    try {
      await assert.rejects(
        discoverDocumentFiles({ directory: outside, workdir }),
        (error: unknown) => error instanceof DocumentNormalizationError &&
          error.code === "document_source_outside_job_workdir"
      );
    } finally {
      await rm(outside, { recursive: true, force: true });
    }
  });
});
