import assert from "node:assert/strict";
import { test } from "node:test";
import { buildPanelAgentPromptFiles } from "../packages/shared/src/panel-agent-prompt-designer";

test("panel agent personalizes child prompts from the work profile", () => {
  const files = buildPanelAgentPromptFiles({
    supervisorName: "蜂后",
    provider: {
      providerName: "DeepSeek",
      baseUrl: "https://api.deepseek.com",
      model: "deepseek-chat"
    },
    interview: {
      industry: "农业无人机植保",
      role: "农场运营负责人",
      dailyWork: "安排飞防任务、评估病虫害风险、复盘产量和成本",
      outputs: "巡田报告、作业计划、客户汇报",
      audience: "农场团队、一线执行人员、客户",
      qualityBar: "数据可追溯、风险清楚、能直接给一线执行",
      workPressure: "判断病虫害风险、生成执行方案",
      outputStyle: "formal"
    },
    profile: {
      summary: [
        "Role: 农场运营负责人",
        "Domain: 农业无人机植保",
        "Work: 安排飞防任务、评估病虫害风险、复盘产量和成本",
        "Audience: 农场团队、一线执行人员、客户",
        "Pressure: 判断病虫害风险、生成执行方案",
        "Output style: formal",
        "Quality: 数据可追溯、风险清楚、能直接给一线执行"
      ].join("\n"),
      stageAgents: ["research-agent", "writer-agent", "test-agent"],
      recommendedRoutingMode: "supervisor_pipeline",
      outputStyle: "formal"
    },
    panelAgentId: "panel-supervisor-agent",
    childAgentIds: ["research-agent", "writer-agent", "test-agent"]
  });

  const researchPrompt = files.find((file) => file.id === "research-agent")?.contents ?? "";
  assert.match(researchPrompt, /generated by the Honeycomb panel agent/);
  assert.match(researchPrompt, /农业无人机植保/);
  assert.match(researchPrompt, /农场运营负责人/);
  assert.match(researchPrompt, /农场团队、一线执行人员、客户/);
  assert.match(researchPrompt, /判断病虫害风险、生成执行方案/);
  assert.match(researchPrompt, /output_style=formal/);
  assert.match(researchPrompt, /数据可追溯、风险清楚、能直接给一线执行/);
  assert.match(researchPrompt, /经验库-资料\.md/);
  assert.match(researchPrompt, /state\/stage-\{stage_number\}-\{type\}-output\.json/);
  assert.match(researchPrompt, /Post-work self-evolution review/);
  assert.match(researchPrompt, /experience_candidate object/);
  assert.match(researchPrompt, /success_pattern, failure_pattern, or agent_lesson/);
  assert.match(researchPrompt, /utility_score/);
  assert.match(researchPrompt, /decay_sensitivity/);
  assert.match(researchPrompt, /capacity_bucket/);
  assert.doesNotMatch(researchPrompt, /api key configured separately/i);

  const panelPrompt = files.find((file) => file.id === "panel-supervisor-agent")?.contents ?? "";
  assert.match(panelPrompt, /# 蜂后/);
  assert.match(panelPrompt, /Prompt-personalization responsibility/);
  assert.match(panelPrompt, /AGENTS\.md must contain the work profile/);
  assert.match(panelPrompt, /post-work self-evolution review/);
  assert.match(panelPrompt, /Capacity control/);
  assert.match(panelPrompt, /Preferred output style: formal/);
  assert.match(panelPrompt, /API key: configured separately; never include it here/);
});
